scene_info = -1;
scene = 0;

timer = 0;

scene_info = [
	[cutscene_create_character, 0, 0, "Instances", obj_cs_dark],
	[cutscene_create_character, 624, 575, "Instances", obj_cs_player],
	[cutscene_create_character, 0, 0, "Instances", obj_cs_camera],
	[cutscene_create_character, 481, 240, "Instances", obj_vyacheslav],
	[cutscene_move_character_to, 624, 576, obj_cs_player, false, 1],
	[cutscene_move_character_to, 480, 240, obj_vyacheslav, false, 1],
	[cutscene_dark_control, 0, true],
	[cutscene_wait, 2],
	[cutscene_play_sound, sound_footsteps, 2, true],
	[cutscene_change_sprite_character, obj_vyacheslav, spr_Vyacheslav_walk],
	[cutscene_move_character_to, 624, 511, obj_vyacheslav, false, 3],
	[cutscene_move_character_to, 624, 512, obj_vyacheslav, false, 1],
	[cutscene_stop_sound, sound_footsteps],
	[cutscene_change_sprite_character, obj_vyacheslav, spr_Vyacheslav_idle],
	[cutscene_wait, 0.5],
	[cutscene_speech_character, "Вячеслав", "Ты опять последний?"],
	[cutscene_speech_character_destroy, obj_textBox],
	[cutscene_speech_character, "Андрей", "Да, я почти всё доделал и смогу всё выслать, наверное, где-то через час. А дальше пусть сами разбираются."],
	[cutscene_speech_character_destroy, obj_textBox],
	[cutscene_speech_character, "Вячеслав", "Домой бы шёл. Ты выглядишь очень плохо."],
	[cutscene_speech_character_destroy, obj_textBox],
	[cutscene_speech_character, "Андрей", "Сейчас кофе сделаю и пройдёт. Потом отосплюсь. Пока."],
	[cutscene_speech_character_destroy, obj_textBox],
	[cutscene_speech_character, "Вячеслав", "Ты не убей себя… Ладно, удачи."],
	[cutscene_speech_character_destroy, obj_textBox],
	[cutscene_wait, 0.5],
	[cutscene_play_sound, sound_footsteps, 2, true],
	[cutscene_change_sprite_character, obj_vyacheslav, spr_Vyacheslav_walk],
	[cutscene_move_character_to, 734, 49, obj_vyacheslav, false, 3],
	[cutscene_move_character_to, 734, 48, obj_vyacheslav, false, 1],
	[cutscene_stop_sound, sound_footsteps],
	[cutscene_change_sprite_character, obj_vyacheslav, spr_Vyacheslav_idle],
	[cutscene_play_sound, sound_door, 2, false],
	[cutscene_destroy_character, obj_vyacheslav],
	[cutscene_wait, 3],
	[cutscene_dark_control, 50, true],
	[cutscene_wait, 1],
	[cutscene_dark_control, 85, true],
	[cutscene_wait, 1],
	[cutscene_dark_control, 100, true],
	[cutscene_wait, 1],
	[cutscene_dark_control, 0, true],
	[cutscene_wait, 0.5],
	[cutscene_speech_character, "Андрей", "Чёрт, едва не уснул! Надо быстрее отправить."],
	[cutscene_speech_character_destroy, obj_textBox],
	[cutscene_wait, 1],
	[cutscene_speech_character, "Андрей", "..."],
	[cutscene_speech_character_destroy, obj_textBox],
	[cutscene_wait, 1],
	[cutscene_speech_character, "Андрей", "Да будь оно неладно, комп завис. Ничего, с другого смогу отправить."],
	[cutscene_speech_character_destroy, obj_textBox],
	[cutscene_wait, 0.5],
	[cutscene_play_sound, sound_footsteps, 2, true],
	[cutscene_change_sprite_character, obj_cs_player, spr_player_shirt_walk],
	[cutscene_move_character_to, 608, 449, obj_cs_player, false, 3],
	[cutscene_move_character_to, 608, 448, obj_cs_player, false, 1],
	[cutscene_stop_sound, sound_footsteps],
	[cutscene_change_sprite_character, obj_cs_player, spr_player_shirt_idle],
	[cutscene_play_sound, sound_door, 2, false],
	[cutscene_create_character, 734, 48, "Instances", obj_vyacheslav],
	[cutscene_move_character_to, 734, 49, obj_vyacheslav, false, 1],
	[cutscene_play_sound, sound_footsteps, 2, true], // не знаю, нужны ли тут шаги
	[cutscene_change_sprite_character, obj_vyacheslav, spr_Vyacheslav_fly],
	[cutscene_move_character_to, 608, 248, obj_vyacheslav, false, 3],
	[cutscene_move_character_to, 608, 249, obj_vyacheslav, false, 1],
	[cutscene_stop_sound, sound_footsteps],
	[cutscene_change_sprite_character, obj_vyacheslav, spr_Vyacheslav_idle],
	[cutscene_wait, 1],
	[cutscene_speech_character, "Андрей", "Слав, ты всё ещё не ушёл?"],
	[cutscene_speech_character_destroy, obj_textBox],
	[cutscene_speech_character, "Вячеслав", "Иди домой."],
	[cutscene_speech_character_destroy, obj_textBox],
	[cutscene_speech_character, "Андрей", "Что?.. Минуту же ещё."],
	[cutscene_speech_character_destroy, obj_textBox],
	[cutscene_wait, 1],
	[cutscene_change_sprite_character, obj_vyacheslav, spr_Vyacheslav_dead],
	[cutscene_wait, 0.5],
	[cutscene_destroy_character, obj_vyacheslav],
	[cutscene_wait, 1],
	[cutscene_dark_control, 90, false],
	//[cutscene_play_sound, sound_pistol, 2, false],
	[cutscene_stop_sound, sound_theme],
	[cutscene_play_sound, sound_office, 1, true],
	[cutscene_wait, 2],
	[cutscene_speech_character, "Андрей", "Что за..?"],
	[cutscene_speech_character_destroy, obj_textBox],
	[cutscene_wait, 1],
	[cutscene_speech_character, "Андрей", "Чего только не привидится от переутомления, однако."],
	[cutscene_speech_character_destroy, obj_textBox],
	[cutscene_speech_character, "Андрей", "Так, похоже, вырубило свет на этаже. Надо спуститься на лифте на этаж ниже и там найти работающий комп."],
	[cutscene_speech_character_destroy, obj_textBox],
	[cutscene_speech_character, "Андрей", "Темень хоть глаз выколи. Хорошо, что у меня с собой фонарик."],
	[cutscene_speech_character_destroy, obj_textBox],
	[cutscene_speech_character, "<F> - вкл/выкл фонарь", ""],
	[cutscene_speech_character_destroy, obj_textBox],
	[cutscene_speech_character, "<E> - взаимодействие", ""],
	[cutscene_speech_character_destroy, obj_textBox],
];

x_dest = -1;
y_dest = -1;